changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - fix
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Other
      labels:
        - '*'
