#!/command/with-contenv bash

if [[ -v TESTING_MODE ]]; then
    export DAEMON_URL=${DAEMON_URL:-https://127.0.0.1:8443/}
    export DAEMON_DEBUG=${DAEMON_DEBUG:-true}
    export DAEMON_VERBOSE=${DAEMON_VERBOSE:-true}
fi

if [[ ! -v DB_HOST ]]; then
    echo "The DB_HOST environment variable must be set." 1>&2
    exit 1
fi

if [[ ! -v DB_PASSWORD ]]; then
    echo "The DB_PASSWORD environment variable must be set." 1>&2
    exit 1
fi

if [[ ! -v DAEMON_URL ]]; then
    echo "The DAEMON_URL environment variable must be set." 1>&2
    exit 1
fi

cat <<EOF > /var/www/movim/.env
DB_DRIVER=${DB_DRIVER}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_DATABASE=${DB_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
DAEMON_URL=${DAEMON_URL}
DAEMON_DEBUG=${DAEMON_DEBUG}
DAEMON_VERBOSE=${DAEMON_VERBOSE}

DAEMON_PORT=8081
DAEMON_INTERFACE=127.0.0.1
EOF

php /var/www/movim/daemon.php start
