name: Build Container Image

on:
  workflow_call:
    inputs:
      movim-tag:
        required: true
        type: string
      publish:
        required: true
        type: boolean

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@5f637c833aa76bc99372a1dc9a6f8bcd8056fb85 # v1.12.0
    permissions:
      contents: read
      packages: write
      #id-token: write
    with:
      push: ${{ inputs.publish }}
      output: image
      setup-qemu: true
      platforms: linux/amd64,linux/arm64
      context: .
      file: Containerfile
      build-args: |
        MOVIM_TAG=${{ inputs.movim-tag }}
      cache: true
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=raw,value=${{ inputs.movim-tag }}
      meta-flavor: |
        latest=${{ startsWith(inputs.movim-tag, 'v') }}
      # Do not spam sha-based image tags. See: https://github.com/docker/github-builder/issues/109
      sign: false
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
