name: Build Master

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-container.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      movim-tag: master
      publish: true
