name: Build Master

on:
  schedule:
    - cron: '0 6 * * *'
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-container.yml
    permissions:
      contents: read
      packages: write
      #id-token: write
    with:
      movim-tag: master
      publish: ${{ github.event_name != 'pull_request' && github.event_name != 'push' }}
